version: "3"
services:
  api-database:
    image: mongo:latest
    container_name: mongo-api-demo
    ports:
      - 27017:27017
  api:
    image: api-demo:latest
    ports:
      - 8080:8080
    links:
      - api-database